# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='agent_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='installed_agent',
            field=models.BooleanField(default=False),
        ),
    ]
