# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0002_auto_20160801_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='entity',
        ),
        migrations.AddField(
            model_name='computer',
            name='entity',
            field=models.ManyToManyField(to='om.Entity'),
        ),
    ]
