# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0003_auto_20160801_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='entity',
        ),
        migrations.AddField(
            model_name='computer',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='om.Entity'),
            preserve_default=False,
        ),
    ]
