# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0005_auto_20160801_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': '\u4e3b\u673a', 'verbose_name_plural': '\u4e3b\u673a'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': '\u5b9e\u4f53', 'verbose_name_plural': '\u5b9e\u4f53'},
        ),
        migrations.AlterModelOptions(
            name='execuser',
            options={'verbose_name': '\u6267\u884c\u7528\u6237', 'verbose_name_plural': '\u6267\u884c\u7528\u6237'},
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'verbose_name': '\u4f5c\u4e1a\u6d41', 'verbose_name_plural': '\u4f5c\u4e1a\u6d41'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '\u4f5c\u4e1a', 'verbose_name_plural': '\u4f5c\u4e1a'},
        ),
        migrations.AlterModelOptions(
            name='jobgroup',
            options={'verbose_name': '\u4efb\u52a1\u7ec4', 'verbose_name_plural': '\u4efb\u52a1\u7ec4'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name': '\u4efb\u52a1', 'verbose_name_plural': '\u4efb\u52a1'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': '\u65e5\u5fd7', 'verbose_name_plural': '\u65e5\u5fd7'},
        ),
        migrations.AlterModelOptions(
            name='logtype',
            options={'verbose_name': '\u65e5\u5fd7\u7c7b\u578b', 'verbose_name_plural': '\u65e5\u5fd7\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': '\u7cfb\u7edf', 'verbose_name_plural': '\u7cfb\u7edf'},
        ),
        migrations.AlterField(
            model_name='computer',
            name='agent_name',
            field=models.CharField(max_length=100, verbose_name='AGENT\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='desc',
            field=models.TextField(verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='entity',
            field=models.ManyToManyField(to='om.Entity', verbose_name='\u6240\u5c5e\u5b9e\u4f53'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='host',
            field=models.CharField(max_length=100, verbose_name='\u4e3b\u673a\u540d'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='installed_agent',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u5b89\u88c5AGENT'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ip',
            field=models.CharField(max_length=100, verbose_name='IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='desc',
            field=models.TextField(verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u5b9e\u4f53\u540d'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='om.System', verbose_name='\u6240\u5c5e\u7cfb\u7edf'),
        ),
        migrations.AlterField(
            model_name='execuser',
            name='desc',
            field=models.TextField(verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='execuser',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u6267\u884c\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='desc',
            field=models.TextField(verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u4f5c\u4e1a\u6d41\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='job',
            name='desc',
            field=models.TextField(verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='job',
            name='exec_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='om.ExecUser', verbose_name='\u6267\u884c\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file_from_local',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u4f7f\u7528\u672c\u5730\u4e0a\u4f20\u7684\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file_target_path',
            field=models.CharField(max_length=100, verbose_name='\u4e0a\u4f20\u76ee\u6807\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='om.JobGroup', verbose_name='\u6240\u5c5e\u4f5c\u4e1a\u7ec4'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='om.JobType', verbose_name='\u4f5c\u4e1a\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u4f5c\u4e1a\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pause_when_error',
            field=models.BooleanField(default=True, verbose_name='\u6267\u884c\u5931\u8d25\u540e\u662f\u5426\u6682\u505c'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pause_when_finish',
            field=models.BooleanField(default=False, verbose_name='\u6267\u884c\u5b8c\u6210\u540e\u662f\u5426\u6682\u505c'),
        ),
        migrations.AlterField(
            model_name='job',
            name='script_content',
            field=models.TextField(verbose_name='\u811a\u672c\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='desc',
            field=models.TextField(verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='om.Flow', verbose_name='\u6240\u5c5e\u4f5c\u4e1a\u6d41'),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u4efb\u52a1\u7ec4\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='desc',
            field=models.TextField(verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u4efb\u52a1\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='log',
            name='content',
            field=models.TextField(verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='log',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='om.LogType', verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_time',
            field=models.DateTimeField(verbose_name='\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='log',
            name='topic',
            field=models.CharField(max_length=100, verbose_name='\u4e3b\u9898'),
        ),
        migrations.AlterField(
            model_name='logtype',
            name='desc',
            field=models.TextField(verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='logtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u65e5\u5fd7\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='system',
            name='desc',
            field=models.TextField(verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u7cfb\u7edf\u540d'),
        ),
    ]
