# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0006_auto_20160802_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='job_type',
            new_name='log_type',
        ),
    ]
