# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0007_auto_20160802_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='founder',
            field=models.CharField(default='NA', max_length=50, verbose_name='\u521b\u5efa\u4eba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='last_modified_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='\u521b\u5efa\u4eba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='last_modified_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
