# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0008_auto_20160825_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='job_group_list',
            field=models.CommaSeparatedIntegerField(default=0, max_length=500, verbose_name='\u4f5c\u4e1a\u7ec4\u987a\u5e8f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flow',
            name='last_modified_by',
            field=models.CharField(max_length=50, verbose_name='\u6700\u540e\u4fee\u6539\u4eba'),
        ),
    ]
