# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0011_auto_20160826_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobgroup',
            name='pause_when_error',
            field=models.BooleanField(default=True, verbose_name='\u6267\u884c\u5931\u8d25\u540e\u662f\u5426\u6682\u505c'),
        ),
        migrations.AddField(
            model_name='jobgroup',
            name='pause_when_finish',
            field=models.BooleanField(default=False, verbose_name='\u6267\u884c\u5b8c\u6210\u540e\u662f\u5426\u6682\u505c'),
        ),
    ]
