# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0013_auto_20160826_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobgroup',
            options={'verbose_name': '\u4f5c\u4e1a\u7ec4', 'verbose_name_plural': '\u4f5c\u4e1a\u7ec4'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name': '\u4f5c\u4e1a\u7c7b\u578b', 'verbose_name_plural': '\u4f5c\u4e1a\u7c7b\u578b'},
        ),
        migrations.AddField(
            model_name='job',
            name='pause_error_tip',
            field=models.CharField(default='\u6267\u884c\u51fa\u9519\uff0c\u8bf7\u786e\u8ba4\u3002', max_length=100, verbose_name='\u6267\u884c\u9519\u8bef\u6682\u505c\u63d0\u793a'),
        ),
        migrations.AddField(
            model_name='job',
            name='pause_finish_tip',
            field=models.CharField(default='\u6267\u884c\u5b8c\u6210\uff0c\u8bf7\u786e\u8ba4\u540e\u7ee7\u7eed\u3002', max_length=100, verbose_name='\u6267\u884c\u5b8c\u6210\u6682\u505c\u63d0\u793a'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='job_group_list',
            field=models.CharField(default='', max_length=500, verbose_name='\u4f5c\u4e1a\u7ec4\u5e8f\u5217'),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u4f5c\u4e1a\u7ec4\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u4f5c\u4e1a\u7c7b\u578b'),
        ),
    ]
