# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0014_auto_20160831_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('SCRIPT', '\u811a\u672c\u6267\u884c'), ('FILE', '\u6587\u4ef6\u4f20\u8f93')], default='SCRIPT', max_length=50, verbose_name='\u4f5c\u4e1a\u7c7b\u578b'),
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
    ]
