# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0015_auto_20160831_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='script_type',
            field=models.CharField(choices=[('PY', 'python\u811a\u672c'), ('SHELL', 'shell\u811a\u672c'), ('BAT', '\u6279\u5904\u7406\u811a\u672c')], default='PY', max_length=50, verbose_name='\u811a\u672c\u7c7b\u578b'),
        ),
    ]
