# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0017_auto_20160905_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='desc',
            field=models.TextField(default='NA', verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file_from_local',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4f7f\u7528\u672c\u5730\u4e0a\u4f20\u7684\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file_target_path',
            field=models.CharField(default='NA', max_length=100, verbose_name='\u4e0a\u4f20\u76ee\u6807\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='job',
            name='script_content',
            field=models.TextField(default='', verbose_name='\u811a\u672c\u5185\u5bb9'),
        ),
    ]
