# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 05:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0019_auto_20160906_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='server_list',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='\u4f5c\u4e1a\u7ec4\u5e8f\u5217'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ip',
            field=models.CharField(max_length=100, validators=[django.core.validators.validate_ipv46_address], verbose_name='IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='job_group_list',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='\u4f5c\u4e1a\u7ec4\u5e8f\u5217'),
        ),
        migrations.AlterField(
            model_name='job',
            name='exec_user',
            field=models.ForeignKey(blank=True, default='deployop', on_delete=django.db.models.deletion.CASCADE, to='om.ExecUser', verbose_name='\u6267\u884c\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='job_list',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='\u4f5c\u4e1a\u7ec4\u5e8f\u5217'),
        ),
    ]
