# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0021_auto_20160907_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='exec_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='om.ExecUser', verbose_name='\u6267\u884c\u7528\u6237'),
        ),
    ]
