# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 07:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0026_auto_20160907_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobgroup',
            name='job_list',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='\u4f5c\u4e1a\u7ec4\u5217\u8868'),
        ),
    ]
