# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0027_auto_20160907_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobgroup',
            name='job_list',
            field=models.CharField(default='', max_length=500, verbose_name='\u4f5c\u4e1a\u7ec4\u5217\u8868'),
        ),
    ]
