# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0028_auto_20160907_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='server_list',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='\u670d\u52a1\u5668\u5217\u8868'),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='job_list',
            field=models.CharField(default='', max_length=500, verbose_name='\u4f5c\u4e1a\u5217\u8868'),
        ),
    ]
