# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 07:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0029_auto_20160909_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='server_list',
            field=models.CharField(blank=True, default='', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='\u670d\u52a1\u5668\u5217\u8868'),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='job_list',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='\u4f5c\u4e1a\u5217\u8868'),
        ),
    ]
