# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0031_auto_20160909_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_type', models.CharField(choices=[('quick_job', '\u5feb\u901f\u4efb\u52a1'), ('work_flow', '\u4f5c\u4e1a\u6d41')], default='work_flow', max_length=50, verbose_name='\u4efb\u52a1\u7c7b\u578b')),
                ('exec_user', models.CharField(default='NA', max_length=100, verbose_name='\u6267\u884c\u4eba')),
                ('exec_content_id', models.TextField(default='', max_length=500, verbose_name='\u6267\u884c\u5185\u5bb9')),
                ('start_time', models.DateTimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('task_status', models.CharField(choices=[('quick_job', '\u5feb\u901f\u4efb\u52a1'), ('work_flow', '\u4f5c\u4e1a\u6d41')], default='no_run', max_length=50, verbose_name='\u5f53\u524d\u72b6\u6001')),
            ],
        ),
    ]
