# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0032_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '\u4efb\u52a1', 'verbose_name_plural': '\u4efb\u52a1'},
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('success', '\u6267\u884c\u6210\u529f'), ('error', '\u6267\u884c\u62a5\u9519'), ('running', '\u6b63\u5728\u6267\u884c'), ('no_run', '\u672a\u6267\u884c')], default='no_run', max_length=50, verbose_name='\u5f53\u524d\u72b6\u6001'),
        ),
    ]
