# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0033_auto_20160912_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='script_param',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u811a\u672c\u53c2\u6570'),
        ),
    ]
