# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0034_job_script_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exec_content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='om.Flow', verbose_name='\u6267\u884c\u5185\u5bb9'),
        ),
    ]
