# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0035_auto_20160912_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='exec_content_id',
            new_name='exec_flow_id',
        ),
    ]
