# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0037_auto_20160912_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='is_quick_flow',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u5feb\u901f\u6267\u884c\u4f5c\u4e1a\u6d41'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
    ]
