# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0038_auto_20160912_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='exec_flow_id',
            new_name='exec_flow',
        ),
    ]
