# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0042_task_curr_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='curr_step',
            field=models.CharField(default='', max_length=200, verbose_name='\u5f53\u524d\u6267\u884c\u4f5c\u4e1a'),
        ),
    ]
