# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0044_auto_20160913_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='pause_when_error',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='pause_when_finish',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pause_error_tip',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pause_when_error',
        ),
        migrations.RemoveField(
            model_name='jobgroup',
            name='pause_when_error',
        ),
        migrations.RemoveField(
            model_name='jobgroup',
            name='pause_when_finish',
        ),
        migrations.RemoveField(
            model_name='task',
            name='curr_step',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_status',
        ),
        migrations.AddField(
            model_name='task',
            name='detail',
            field=models.TextField(default='', verbose_name='\u6267\u884c\u7ec6\u8282'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('finish', '\u5df2\u6267\u884c'), ('running', '\u6b63\u5728\u6267\u884c'), ('no_run', '\u672a\u6267\u884c')], default='no_run', max_length=50, verbose_name='\u5f53\u524d\u72b6\u6001'),
        ),
    ]
